image: maven:3.5.4-jdk-8

stages:
  - setup
  - compile

setup:
  stage: setup
  script: java -version > java-version.txt
  artifacts:
    paths:
    - java-version.txt
  script: curl https://raw.githubusercontent.com/creationix/nvm/v0.25.0/install.sh | bash
  script: source ~/.bashrc
  script: nvm install 8.9

  
compile:
  stage: compile
  script: bash $CI_PROJECT_DIR/build-gitlab.sh


