image: maven:3.5.4-jdk-8

stages:
  - setup
  - compile

setup:
  stage: setup
  script: echo `java -version`
  script: nvm install 8.9
  
compile:
  stage: compile
  script: bash $CI_PROJECT_DIR/build-gitlab.sh


