language: java
jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.m2

env:
  - NODE_VERSION="8.9"

before_install:
  - nvm install $NODE_VERSION
  - node --version
  - npm --version
  - bash ./build.sh

